---
title: "R Notebook"
output: html_notebook
---

## Introduction


Data can be not only useful but also beautiful. This article points to some of the starting points for those who want to explore generative art in R.

Generative art represents the involvement of a human-independent system (such as an algorithm) in a creative process. Such a system is a key element within the creative process, including its outputs.
Unsurprisingly, there are many “tools” you can use if you want to delve into generative art. In case you want to have “hands-on” experience in R, there are two basic directions you can go.
If you are a person proficient in working with code, you may write your code straight away. I dare to argue that this is the way of the “individual” expression as it allows for more flexibility, and, well, freedom.
However, getting to that point takes time. Luckily, you can begin experimenting with your pieces of generative art by using one of the existing packages. Not only it could be quite rewarding, but it also works perfectly for grasping the basics of the “trade”.
In this article, I am going to present to you some of the “ready-to-use” packages for making generative art. Also, I will tap into some of the examples of using general packages or libraries to arrive at the same goal.


Outside of data visualization, more abstract pieces are created. I'd say data is still important, but the information is more hidden or being described in a dimension that isn't easily understood.

My first encounter was finding the website by Antonio Chinchon of Fronkonstin. Who I have found has created some wonderful blog posts describing in detail the process of the work that he has created using R.


And there are many more, Thomas Pedersen, Danielle Navarro, Paul Vanderlaken, or Antonio Chinchon, and others who have created art in the R space.

So even though this tool has always been more about data processing than creating; I think there are a few interesting arguments that using R might be another great tool for generative art.


## General-purpose packages
In many instances, previously mentioned packages built on more generally used packages such as magritr (the pipeline operator comes in handy even in the art creation), ggplot, dplyr, or purr.


## jasmines

Danielle Navarro, the author of the Learning Statistics with R Learning Statistics with R handbook, is a well-known person among psychology students.
Besides her teaching and research activities at the University of Adelaide, she also released the jasmines package, a tool allowing for creating a generative art in R.
This package gives you an opportunity to play with simulation parameters (e.g. grain or interaction), shapes (e.g. entity_circle or scene_discs) and their modifications (like style_ribbon) or colours (palette or alpha). 

## generativeart

The first package I would like to present is called simply generativeart.
One of its key features is the way how it structures the output files. In order to get the output files, you have to specify the location where they will be stored. Also, it iterates on the provided formula that doesn’t need to be supported with a seed. In this scenario, each of the outcome files is unique.


## aRtsy

aRtsy aims to make generative art accessible to the general public in a straightforward and standardized manner. The package provides algorithms for creating artworks that incorporate some form of randomness and are dependent on the set seed. Each algorithm is implemented in a separate function with its own set of parameters that can be tweaked.

## References

https://towardsdatascience.com/getting-started-with-generative-art-in-r-3bc50067d34b

https://generative.substack.com/p/generative-art-and-r

https://github.com/koenderks/aRtsy

https://blog.djnavarro.net/posts/2021-07-08_generative-art-in-r/